# Generated by Django 5.2.13 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_categories_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
